
const BLOGLIST_REQUESTED = 'all/BLOGLIST_REQUESTED';
const BLOGLIST_RECEIVED = 'all/BLOGLIST_RECEIVED';
const BLOGLIST_ERROR = 'all/BLOGLIST_ERROR';
const BLOG_REQUESTED = 'one/BLOG_REQUESTED';
const BLOG_RECEIVED = 'one/BLOG_RECEIVED';
const BLOG_ERROR = 'one/BLOG_ERROR';


const Actions = {
  BLOGLIST_REQUESTED,
  BLOGLIST_RECEIVED,
  BLOGLIST_ERROR,
  BLOG_REQUESTED,
  BLOG_RECEIVED,
  BLOG_ERROR
};

export default Actions;

