
const BLOGLIST_REQUESTED = 'all/BLOGLIST_REQUESTED';
const BLOGLIST_RECEIVED = 'all/BLOGLIST_RECEIVED';
const BLOGLIST_ERROR = 'all/BLOGLIST_ERROR';
const BLOG_REQUESTED = 'one/BLOG_REQUESTED';
const BLOG_RECEIVED = 'one/BLOG_RECEIVED';
const BLOG_ERROR = 'one/BLOG_ERROR';
const COMMENT_REQUESTED = 'one/COMMENT_REQUESTED';
const COMMENT_RECEIVED = 'one/COMMENT_RECEIVED';
const COMMENT_ERROR = 'one/COMMENT_ERROR';


const Actions = {
  BLOGLIST_REQUESTED,
  BLOGLIST_RECEIVED,
  BLOGLIST_ERROR,
  BLOG_REQUESTED,
  BLOG_RECEIVED,
  BLOG_ERROR,
  COMMENT_REQUESTED,
  COMMENT_RECEIVED,
  COMMENT_ERROR
};

export default Actions;

